### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by FathimaShifnaK** [sodipto/flutter-phone-state-background#12]
I got an error while trying to call _init().
Unhandled Exception: Null check operator used on a null value
E/flutter ( 8879): #0      PhoneStateBackground.initialize (package:phone_state_background/phone_state_background.dart:32:24)

**Comment by sodipto** [comment]
@FathimaShifnaK provide full error stack trace.

**Comment by FathimaShifnaK** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
    #0      PhoneStateBackground.initialize (package:phone_state_background/phone_state_background.dart:32:24)
    <asynchronous suspension>
    #1      CallRecordingState._init (package:renault_service_app/call_recording.dart:98:5)
    <asynchronous suspension>
2023-07-12 11:28:34.140 25291-25336/com.example.renault_service_app E/flutter: [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
    #0      PhoneStateBackground.initialize (package:phone_state_background/phone_state_background.dart:32:24)
    <asynchronous suspension>
    #1      CallRecordingState._init (package:renault_service_app/call_recording.dart:98:5)
    <asynchronous suspension>
